// Auth
export const AUTH_REQUEST = "@@AUTHREDUCER/AUTH_REQUEST"
export const AUTH_SUCCESS = "@@AUTHREDUCER/AUTH_SUCCESS"
export const AUTH_FAIL = "@@AUTHREDUCER/AUTH_FAIL"

export const SIGNUP_REQUEST = "@@AUTHREDUCER/SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "@@AUTHREDUCER/SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "@@AUTHREDUCER/SIGNUP_FAIL"

export const SIGNIN_REQUEST = "@@AUTHREDUCER/SIGNIN_REQUEST"
export const SIGNIN_SUCCESS = "@@AUTHREDUCER/SIGNIN_SUCCESS"
export const SIGNIN_FAIL = "@@AUTHREDUCER/SIGNIN_FAIL"

// Project
export const LIST_PROJECT_REQUEST = "@@PROJECTREDUCER/LIST_PROJECT_REQUEST"
export const LIST_PROJECT_SUCCESS = "@@PROJECTREDUCER/LIST_PROJECT_SUCCESS"
export const LIST_PROJECT_FAIL = "@@PROJECTREDUCER/LIST_PROJECT_FAIL"